package com.autoresolve.mediabuying.controller.api;

import com.autoresolve.mediabuying.model.dto.InsightDTO;
import com.autoresolve.mediabuying.service.InsightsEngine;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

/**
 * REST controller exposing AI-generated insights for the Media Buying dashboard.
 */
@RestController
@RequestMapping("/api/insights")
public class InsightsController {

    private final InsightsEngine insightsEngine;

    public InsightsController(InsightsEngine insightsEngine) {
        this.insightsEngine = insightsEngine;
    }

    /**
     * Returns client gap / opportunity / risk insights generated by the LLM engine.
     *
     * @return list of insights
     */
    @GetMapping("/client-gaps")
    @PreAuthorize("hasAnyRole('ADMIN','MEDIA_ANALYST','VIEWER')")
    public ResponseEntity<List<InsightDTO>> getClientGapInsights() {
        List<InsightDTO> insights = insightsEngine.getClientGapInsights();
        return ResponseEntity.ok(insights);
    }
}
